name: Michelle Fagan Photography
favicon: null
layout_spectrum: 0.009091958869248629
typography_spectrum: 0.0608471711166203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6732334364205599
  lightness: 0.004160539014264941
  saturation: 0.027809697668999434
  rhythmicContrast: 0.018227638909593225
purpose: []
